[package]
name = "group-shuffle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
thiserror = "1.0.49"
rand = { version = "0.8.5", features = ["small_rng"] }
